// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwzAkpvwvGI6NRfr1UZ4_TaZDbGpvWAc',
    appId: '1:493628678652:web:61873f118359d2ce4b9279',
    messagingSenderId: '493628678652',
    projectId: 'moviebrowser-d3c10',
    authDomain: 'moviebrowser-d3c10.firebaseapp.com',
    storageBucket: 'moviebrowser-d3c10.firebasestorage.app',
    measurementId: 'G-473XFM9DLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzXf9HT2L-yLk4hIehF5YtOxxfGV5ntV0',
    appId: '1:493628678652:android:2cd943691b14cbbb4b9279',
    messagingSenderId: '493628678652',
    projectId: 'moviebrowser-d3c10',
    storageBucket: 'moviebrowser-d3c10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtWpMUZwEFQgGTc6MkJTzZEYKZFnEVAow',
    appId: '1:493628678652:ios:c092eace9f7144d04b9279',
    messagingSenderId: '493628678652',
    projectId: 'moviebrowser-d3c10',
    storageBucket: 'moviebrowser-d3c10.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtWpMUZwEFQgGTc6MkJTzZEYKZFnEVAow',
    appId: '1:493628678652:ios:c092eace9f7144d04b9279',
    messagingSenderId: '493628678652',
    projectId: 'moviebrowser-d3c10',
    storageBucket: 'moviebrowser-d3c10.firebasestorage.app',
    iosBundleId: 'com.example.movieBrowser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwzAkpvwvGI6NRfr1UZ4_TaZDbGpvWAc',
    appId: '1:493628678652:web:9e90b9a88c03be4a4b9279',
    messagingSenderId: '493628678652',
    projectId: 'moviebrowser-d3c10',
    authDomain: 'moviebrowser-d3c10.firebaseapp.com',
    storageBucket: 'moviebrowser-d3c10.firebasestorage.app',
    measurementId: 'G-HJZ5BQLQ2Z',
  );
}
